export const API_URLS = {
  signup: "auth/signup",
  login: "auth/signin",
  refreshToken: "auth/refresh-token",
  logout: "auth/logout",
  checkToken: "auth/checkToken",
  forgotPassword: "auth/forgot-password",
  resetPassword: "auth/reset-password",
  createTask: "tasks",
  deleteTask: "tasks",
  editTask: "tasks",
  getAllTasks: "tasks",
  getAllUsers: "users/getAllUsers",
  getAllRoles: "roles",
};
